add kafka module to jooby
jooby-project/jooby pull request #2089
Opened 2020-10-29 10:54 UTC by kindywu

/**
   * Creates a new kafka producer module using the <code>kafka.producer</code> property key.
   * This key must be present in the application configuration file, like:
   *
   * <pre>{@code
   *  kafka.producer.bootstrap.servers = "localhost:9092"
   *  kafka.producer.acks = "all"
   *  kafka.producer.retries = 0
   *  kafka.producer.key.serializer = "org.apache.kafka.common.serialization.StringSerializer"
   *  kafka.producer.value.serializer = "org.apache.kafka.common.serialization.StringSerializer"
   * }</pre>
   *
   * Creates a new kafka consumer module using the <code>kafka.consumer</code> property key.
   * This key must be present in the application configuration file, like:
   *
   * <pre>{@code
   *  kafka.consumer.bootstrap.servers = "localhost:9092"
   *  kafka.consumer.group.id = "group A"
   *  kafka.consumer.key.deserializer = "org.apache.kafka.common.serialization.StringDeserializer"
   *  kafka.consumer.value.deserializer = "org.apache.kafka.common.serialization.StringDeserializer"
   * }</pre>
   */

2020-10-30 12:26 UTC, imeszaros requested changes
Beside the minor things I commented I find this okay (though I'm not familiar with Kafka)!

2020-10-30 12:26 UTC, imeszaros commented on modules/jooby-kafka/src/main/java/io/jooby/kafka/KafkaModule.java
> + */
Please replace the docs copied from Redis module with proper docs.

2020-10-30 12:26 UTC, imeszaros commented on modules/jooby-kafka/src/main/java/io/jooby/kafka/KafkaModule.java
> +    Properties props = new Properties();
You could throw an exception if `key` argument is `null`, since it means an improper configuration.

2020-10-30 12:26 UTC, imeszaros commented on modules/jooby-kafka/src/main/java/io/jooby/kafka/KafkaModule.java
> +    }
You could throw an exception in an `else` block here, since this also means that configuration properties are missing.

2020-11-11 17:03 UTC, jknack commented
Going to merge and cleanup

2020-11-11 17:03 UTC, merged